# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fded0937-3762-43b5-989b-5a5f9db4c55b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0334-7D60";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Network
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Additional wifi firmware
  #hardware.firmware = [
  #  (
  #    let
  #      ath11_file = builtins.fetchurl {
  #        url = "https://github.com/kvalo/ath11k-firmware/raw/540105aa5c0903b5f773d4e80b8501e8da5217e7/WCN6855/hw2.0/board-2.bin";
  #        sha256 = "1wrygyhakjgk7icwv5wqri54zbss8fw7qmn8f197jbha4wx2qqdj";
  #      };
  #    in
  #      pkgs.runCommandNoCC "ath11k_blade" {} ''
  #       mkdir -p $out/lib/firmware/WCN6855/hw2.0/
  #       cp ${ath11_file} $out/lib/firmware/WCN6855/hw2.0/board-2.bin
  #    ''
  #  )
  #];
}
